# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JkH7fze7NaYYKyO423MBA6ggTHrpZkCN
"""

Day three lienerPreduction

import numpy as np
import pandas as pd

from google.colab import files
uploaded=files.upload()

dataSet=pd.read_csv('DataSet.csv')
print(dataSet)

print(dataSet.shape)

print(dataSet.head(6))

print(dataSet.tail(5))

X=dataSet.iloc[:,:-1].values
print(X)

Y=dataSet.iloc[:,-1].values
print(Y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

print(X_train)

print(X_test)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

print(X_train)

print(X_test)

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

"""After train the model 
Now going to test the model with X test data 
try to predict Y_test Dataset use after Xtest data test

"""

y_pred=model.predict(X_test)

"""Check accuracy of the model by compaire y_pred/y_test*100

"""

from sklearn.metrics import accuracy_score
print('accuracy of the test is :{0}%'.format(accuracy_score(y_test, y_pred)*100))

"""user testing 


"""

salary =int(input('Enter Salary'))
age = int(input('Enter Age '))
newCust=[[salary,age]]
result=model.predict(sc.transform(newCust))
print(result)